### ISSUE TITLE
Feature suggestion: configurable base directory

### ISSUE THREAD

**Issue by vauhochzett** [glad-dev/dn#1]
It's relatively easy to configure dn's base directory, as it reads DN_HOME (and the script can of course just be adapted).

Maybe it makes sense to either read DN_HOME as well or to allow configuring the base directory (potentially before building)?

**Comment by glad-dev** [comment]
Thank you for your suggestion. The feature has been added.

The notes' storage location can be set with the environment variable `DN_HOME`, which is expected to be an absolute path.

The feature was added in commit 31d9809d232c44771cb55fea53774d5a56650e37.
