### ISSUE TITLE
Bug: Version short flag is not capitalized anymore (-v instead of -V)

### ISSUE THREAD

**Issue by vauhochzett** [glad-dev/dn#11]
See #4. The short flag for "version" is now `-v` instead of `-V`.

**Comment by glad-dev** [comment]
Unfortunately, this is a `won't fix` since the version flag is provided by cobra and lowercase by default. That's one of the reasons why v1.6 was supposed to be v2.0 to indicate breaking changes like these.

**Comment by vauhochzett** [comment]
Fair game! Interesting that certain tools are really opinionated on that. Of course I'm used to Python's argparse, but so far cobra really goes against my expectations. :grin:
