### ISSUE TITLE
Regression: Commands now listed alphabetically instead of semantically

### ISSUE THREAD

**Issue by vauhochzett** [glad-dev/dn#13]
This may be intended, so feel free to close: Commands in the `--help` are now listed alphabetically, with some rather unimportant ones (e.g., config) before core ones (e.g., today).

**Comment by glad-dev** [comment]
This is a won't fix. Nevertheless, thank you very much for your feedback.

The ordering is done by cobra, not me. However, sorting the commands alphabetically makes it easier to find a certain argument.

**Comment by vauhochzett** [comment]
Understandable! I have to say, the more I learn about cobra, the more I like Python's argparse, which uses the order you give the arguments or modes to list them. :)
