### ISSUE TITLE
Regression bug: Using a flag leads to error "Multiple flags used"

### ISSUE THREAD

**Issue by vauhochzett** [glad-dev/dn#3]
In the new version, using any flag leads to the error "Multiple flags used".

Reproduce:
```
$ dn -t
Mutiple flags used
[...]
```

In the old version, the same command worked.

**Comment by glad-dev** [comment]
Sorry about that, the issue has been fixed in commit 6727f94c80b22bcaaf0481d2bea45dd72aa616ec.
