### ISSUE TITLE
Suggestion: "verbose" flag or disabling verbose output

### ISSUE THREAD

**Issue by vauhochzett** [glad-dev/dn#9]
This issue is something that really depends on your preference – feel free to discard.

Adding a note currently leads to two lines of output being printed. The note is echoed and a short blurb notes how the operation could be undone.

After the first time, this output is not useful anymore. I would therefore suggest a flag `-v` that activates verbosity. In that mode, the output is printed. Otherwise, not output is printed.

**Alternatively**, in my view, this output could also just be removed.

**Comment by glad-dev** [comment]
If've added the option to disable the output, with `dn config silentAdd true`. Afterwards, `dn "An interesting note"` will not print any output.

**Comment by vauhochzett** [comment]
At first I thought: "a large changeset for such a small suggestion", but I noticed that you also revamped the argument parsing in the same commit :grin:

**Comment by glad-dev** [comment]
Adding the configuration required the introduction of new commands to update it, which would have made the argument parsing even messier. Thus, I decided to rewrite the parsing with [cobra](https://github.com/spf13/cobra).

**Comment by vauhochzett** [comment]
Would it have been easier by just using environment variables, like `DN_HOME`? E.g., `DN_SILENT`.

**Comment by glad-dev** [comment]
Yes, it would have been significantly easier. Unfortunately, I didn't think of that.

**Comment by vauhochzett** [comment]
Makes me realize why [tz](https://github.com/oz/tz/) uses an environment variable for its configured timezones, to reduce complexity!
